-- PDV Gráfica & Copiadora - Supabase
-- Execute este arquivo no SQL Editor do seu projeto Supabase.
-- Depois configure Auth e as políticas RLS conforme o README.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null,
  username text unique,
  role text not null default 'OPERATOR' check (role in ('ADMIN','OPERATOR')),
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.products (
  id text primary key,
  name text not null,
  category text not null,
  price numeric(12,2) not null default 0,
  icon text,
  stock numeric(12,3),
  controls_stock boolean not null default false,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.customers (
  id text primary key,
  name text not null,
  cpf text,
  phone text,
  type text not null check (type in ('MENSALISTA','CREDITO_ANTECIPADO')),
  monthly_limit numeric(12,2) not null default 0,
  monthly_used numeric(12,2) not null default 0,
  monthly_usage_month text,
  credit_balance numeric(12,2) not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists customers_cpf_unique on public.customers(cpf) where cpf is not null and cpf <> '';

create table if not exists public.sales (
  id text primary key,
  sale_date timestamptz not null default now(),
  operator_id uuid references public.profiles(id),
  operator_username text,
  operator_name text,
  customer text,
  customer_id text references public.customers(id) on delete set null,
  customer_type text not null default 'CONSUMIDOR',
  subtotal numeric(12,2) not null default 0,
  discount numeric(12,2) not null default 0,
  total numeric(12,2) not null default 0,
  pay_method text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.sale_items (
  id bigint generated by default as identity primary key,
  sale_id text not null references public.sales(id) on delete cascade,
  product_id text,
  product_name text not null,
  quantity numeric(12,3) not null,
  unit_price numeric(12,2) not null,
  total numeric(12,2) not null
);

create table if not exists public.credit_transactions (
  id uuid primary key default gen_random_uuid(),
  customer_id text not null references public.customers(id) on delete cascade,
  type text not null check (type in ('CREDIT','DEBIT')),
  amount numeric(12,2) not null check (amount > 0),
  sale_id text references public.sales(id) on delete set null,
  operator_id uuid references public.profiles(id),
  note text,
  created_at timestamptz not null default now()
);

create index if not exists sales_date_idx on public.sales(sale_date desc);
create index if not exists sale_items_sale_idx on public.sale_items(sale_id);
create index if not exists credit_customer_idx on public.credit_transactions(customer_id, created_at desc);

-- RLS: somente usuários autenticados.
alter table public.profiles enable row level security;
alter table public.products enable row level security;
alter table public.customers enable row level security;
alter table public.sales enable row level security;
alter table public.sale_items enable row level security;
alter table public.credit_transactions enable row level security;

-- Policies iniciais. A regra de ADMIN/OPERATOR será refinada na próxima etapa.
drop policy if exists "authenticated profiles" on public.profiles;
create policy "authenticated profiles" on public.profiles for all to authenticated using (true) with check (true);

drop policy if exists "authenticated products" on public.products;
create policy "authenticated products" on public.products for all to authenticated using (true) with check (true);

drop policy if exists "authenticated customers" on public.customers;
create policy "authenticated customers" on public.customers for all to authenticated using (true) with check (true);

drop policy if exists "authenticated sales" on public.sales;
create policy "authenticated sales" on public.sales for all to authenticated using (true) with check (true);

drop policy if exists "authenticated sale items" on public.sale_items;
create policy "authenticated sale items" on public.sale_items for all to authenticated using (true) with check (true);

drop policy if exists "authenticated credit transactions" on public.credit_transactions;
create policy "authenticated credit transactions" on public.credit_transactions for all to authenticated using (true) with check (true);

-- Observação: estas policies são deliberadamente simples para a fase de montagem.
-- Antes de colocar o PDV em produção, substituiremos por policies baseadas em role.
